language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq curl
    - git clone https://github.com/oric-software/buildTestAndRelease.git
    - git clone https://github.com/cc65/cc65.git
    - cd cc65 && make && sudo make install PREFIX=/usr && cd ..
after_success:
    - VERSION=`cat VERSION`    
    - cd mym && tar -c * > ../mym.tar &&	cd ..
    - gzip mym.tar
    - mv mym.tar.gz mym.tgz
    - curl -X POST --data-binary '@mym.tgz' "https://cdn.oric.org/publish.php?hash=$hash&path=/home/oricoujr/www/ftp/orix/dists/alpha/tgz/6502/mym.tgz"